### ISSUE TITLE
Access Error?  pip install git+ssh://git@github.com/baaivision/NOVA.git

### ISSUE THREAD

**Issue by Glenn1963** [baaivision/NOVA#1]
Running command git clone --filter=blob:none --quiet 'ssh://****@github.com/baaivision/NOVA.git' 'C:\Users\viewt\AppData\Local\Temp\pip-req-build-wjx2l40k'
  Host key verification failed.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.

**Comment by PhyscalX** [comment]
Hi, @Glenn1963 

Following official [Github Doc](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys), you should set your Github access ssh key for``git+ssh`` URI scheme.
Otherwise, please clone our repository and run ``pip install .`` (i.e., ``From Source``).

**Comment by Glenn1963** [comment]
Thanks PhyscalX, I appreciate the quick reply. Totally my lack of knowledge. With your suggestion and some help from AI I was able to get it to install using ssh. 

Thanks so much!
